# -*- coding: utf-8 -*-
"""MachineLearning_FinalProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aZrSvAm1G0HpIAxnE-3llDwSI6KnnkeO
"""

# 📌 套件匯入
import pandas as pd
import os

# 📌 讀取 CSV 資料
df = pd.read_csv("/content/test.csv", nrows=5000)  # 為測試可先讀取前 5000 筆
print("資料讀取完成，前五筆資料：")
print(df.head())

# 📌 轉換時間欄位為 datetime 型別
df['time'] = pd.to_datetime(df['time'])
print("\n時間欄位轉換完成：")
print(df['time'].dtypes)

# 📌 資料概覽
print("\n資料集資訊：")
print(df.info())
print("\n欄位統計描述：")
print(df.describe(include='all'))

# ===============================
# 1️⃣ 教師式學習用：依 enroll_id 聚合特徵
# ===============================
# 每個學習者的總行為數、唯一行為種類、互動會話數、活動時間跨度
agg_supervised = df.groupby('enroll_id').agg(
    total_actions=('action', 'count'),  # 總行為數
    unique_actions=('action', pd.Series.nunique),  # 不同的行為種類數
    session_count=('session_id', pd.Series.nunique),  # 互動會話數
    first_activity=('time', 'min'),  # 最早活動時間
    last_activity=('time', 'max')    # 最晚活動時間
).reset_index()

# 計算活動天數跨度
agg_supervised['activity_span_days'] = (agg_supervised['last_activity'] - agg_supervised['first_activity']).dt.days

# 刪除暫時不需要的欄位
agg_supervised.drop(columns=['first_activity', 'last_activity'], inplace=True)

# 新增退課標籤（truth）
agg_supervised['dropout'] = df.groupby('enroll_id')['truth'].first().values

print("教師式學習特徵聚合完成：")
print(agg_supervised.head())

# ===============================
# 📌 1️⃣ 教師式學習模型訓練（退課預測）
# ===============================
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# 特徵與標籤
features = ['unique_actions', 'session_count', 'activity_span_days']
X = agg_supervised[features]
y = agg_supervised['dropout']

# 切分訓練集與測試集
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# -------------------------------
# (A) 邏輯斯迴歸模型
# -------------------------------
log_model = LogisticRegression(max_iter=1000, class_weight='balanced')
log_model.fit(X_train, y_train)
y_pred_log = log_model.predict(X_test)

print("📌 Logistic Regression Classification Report:")
print(classification_report(y_test, y_pred_log))

# 混淆矩陣
conf_matrix_log = confusion_matrix(y_test, y_pred_log)
plt.figure(figsize=(6,4))
sns.heatmap(conf_matrix_log, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Retained','Dropped'], yticklabels=['Retained','Dropped'])
plt.title("Logistic Regression Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# -------------------------------
# (B) 決策樹模型
# -------------------------------
tree_model = DecisionTreeClassifier(max_depth=4, random_state=42)
tree_model.fit(X_train, y_train)
y_pred_tree = tree_model.predict(X_test)

print("📌 Decision Tree Classification Report:")
print(classification_report(y_test, y_pred_tree))

plt.figure(figsize=(14,8))
plot_tree(tree_model, feature_names=features, class_names=['Retained','Dropped'],
          filled=True, rounded=True)
plt.title("Decision Tree Visualization")
plt.show()

# ===============================
# 2️⃣ 非教師式學習用：行為聚合供分群分析
# ===============================
# 聚合特徵可以與教師式相同，但不包含標籤
agg_unsupervised = df.groupby('enroll_id').agg(
    total_actions=('action', 'count'),
    unique_actions=('action', pd.Series.nunique),
    session_count=('session_id', pd.Series.nunique),
    first_activity=('time', 'min'),
    last_activity=('time', 'max')
).reset_index()

agg_unsupervised['activity_span_days'] = (agg_unsupervised['last_activity'] - agg_unsupervised['first_activity']).dt.days
agg_unsupervised.drop(columns=['first_activity', 'last_activity'], inplace=True)

print("非教師式學習特徵聚合完成：")
print(agg_unsupervised.head())

# ===============================
# 📌 2️⃣ 非教師式學習（KMeans 分群）
# ===============================
from sklearn.cluster import KMeans

# 使用行為特徵進行分群（不包含標籤）
X_cluster = agg_unsupervised[features]

kmeans = KMeans(n_clusters=3, random_state=42)
agg_unsupervised['cluster'] = kmeans.fit_predict(X_cluster)

# 查看各群的平均行為特徵
cluster_summary = agg_unsupervised.groupby('cluster')[features].mean()
print("📊 Cluster Average Feature Values:")
print(cluster_summary)

# 可視化分群結果（例如 session_count vs activity_span_days）
plt.figure(figsize=(8,6))
sns.scatterplot(data=agg_unsupervised, x='session_count', y='activity_span_days',
                hue='cluster', palette='Set2', s=100)
plt.title("KMeans Clustering Visualization")
plt.xlabel("Session Count")
plt.ylabel("Activity Span (days)")
plt.show()